language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t deshawareswap9/docker-react -f Dockerfile.dev . #this gives id of the docker, that's why -t

script:
  - docker run deshawareswap9/docker-react npm run test -- --coverage