language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t deshawareswap9/docker-react -f Dockerfile.dev . #this gives id of the docker, that's why -t

script:
  - docker run deshawareswap9/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-011159007987"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY